import os
import webbrowser

import yaml


def generate_missing_report_page(report_folder: str, script_name: str, verbose: bool = False) -> None:
    missing_report_path = os.path.join(report_folder, "missing_report.html")

    if not os.path.exists(missing_report_path):
        with open(missing_report_path, "w", encoding="utf-8") as file:
            file.write(
                f"""<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Missing Code Complexity Report</title>
  <style>
    body {{
        font-family: Arial, sans-serif;
        text-align: center;
        margin: 0;
        padding: 0;
    }}
    h2 {{
        margin-top: 20px;
    }}
    p {{
        font-size: 16px;
    }}
    footer {{
        margin-top: 20px;
        font-size: 12px;
        color: #555;
    }}
  </style>
 </head>
 <body>
    <h2>Missing Code Complexity Report for This Module</h2>
    <p>
        A Code Complexity Metrics (CCMR) report has not been generated for this module. Please check if the
        <strong>ccmr</strong> target is being executed for this module or if it is properly configured to generate the report.
    </p>
    <footer>
        Generated by {script_name} script configured with config.yaml
    </footer>
 </body>
</html>
"""
            )
        if verbose:
            print(f"Created missing report page: {missing_report_path}")
    else:
        if verbose:
            print(f"Missing report page already exists: {missing_report_path}")


def generate_main_report(report_folder: str, modules_yaml_file: str, script_name: str, verbose: bool = False) -> None:
    with open(modules_yaml_file, "r") as yaml_file:
        config_data = yaml.safe_load(yaml_file)

    modules = config_data["modules"]
    main_report_path = os.path.join(report_folder, "index.html")

    with open(main_report_path, "w", encoding="utf-8") as file:
        file.write(
            """<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Project Code Complexity Reports Main Page</title>
  <style>
    body {
        font-family: Arial, sans-serif;
        text-align: center;
        margin: 0;
        padding: 0;
    }
    h2 {
        margin-top: 20px;
    }
    ul {
        list-style-type: none;
        padding: 0;
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 10px;
        max-width: 80%;
        margin: 0 auto;
    }
    li {
        margin: 10px 0;
    }
    a {
        text-decoration: none;
    }
    .report-button {
        display: inline-block;
        padding: 15px 25px;
        margin: 5px;
        background-color: #007BFF;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
        text-align: center;
        font-size: 16px;
        box-sizing: border-box;
    }
    .report-button:hover {
        background-color: #0056b3;
    }
    .report-button-missing {
        background-color: #999;
    }
    .report-button-missing:hover {
        background-color: #777;
    }
    footer {
        margin-top: 20px;
        font-size: 12px;
        color: #555;
    }

    @media screen and (max-width: 1000px) {
        ul { grid-template-columns: repeat(3, 1fr); }
    }
    @media screen and (max-width: 600px) {
        ul { grid-template-columns: repeat(2, 1fr); }
    }
    @media screen and (max-width: 400px) {
        ul { grid-template-columns: 1fr; }
    }
  </style>
 </head>
 <body>
    <h2>Project Code Complexity Reports</h2>
    <ul>
"""
        )

        for module in modules:
            module_name = module["name"] if isinstance(module, dict) else str(module)

            report_file = f"{module_name}.html"
            file_path = os.path.join(report_folder, report_file)

            files_in_directory = os.listdir(report_folder)
            matching_files = [fn for fn in files_in_directory if fn.lower() == report_file.lower()]

            if matching_files:
                file_path = os.path.join(report_folder, matching_files[0])
                if verbose:
                    print(f"Found report for module: {module_name} -> {file_path}")
                file.write(
                    f'<li><a href="file://{os.path.abspath(file_path)}"><button class="report-button">{module_name}</button></a></li>\n'
                )
            else:
                if verbose:
                    print(f"Missing report for module: {module_name}")
                missing_report_path = "missing_report.html"
                file.write(
                    f'<li><a href="{missing_report_path}"><button class="report-button report-button-missing">{module_name}</button></a></li>\n'
                )

        file.write(
            f"""    </ul>
    <footer>
        Generated by {script_name} script configured with config.yaml
    </footer>
 </body>
</html>
"""
        )

    if verbose:
        print(f"Wrote main report: {main_report_path}")


def open_html_files_in_default_browser(reports):
    for report in reports:
        try:
            webbrowser.open(f"file://{os.path.abspath(report)}", new=2)
        except Exception:
            pass
